#!/bin/bash

BASE=/Users/owen/cs/dev/pm/
CONF=$BASE/pmd_rsc/pmd.conf

if [ ! -e $BASE"/.version" ]; then 
    echo "No pm version set. echo [VERSION] > .version to rectify" 
    exit 1 
fi 

TARG=pm$(cat $BASE"/.version")

$BASE/bins/$TARG $CONF $*
